### ISSUE TITLE
   expiry = datetime.now().timestamp() + 115 AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

### ISSUE THREAD

**Issue by HypePickups** [ryan9918/captcha-harvester#1]
Hello I am currently running python 2.7 and I was wondering what I could use instead of 
expiry = datetime.now().timestamp() + 115  becuase timestamp does not work for python 2.7 and only 3 

 expiry = datetime.now().timestamp() + 115 AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

what could I replace this with Please help thanks

**Comment by ryan9918** [comment]
Try `time.time() + 115`
